### ISSUE TITLE
How to install gfaestus

### ISSUE THREAD

**Issue by Overcraft90** [chfi/gfaestus#10]
Hi @chfi,

I just got my 2D layout for a human pangenome using `odgi`. Just wondering how can I install `gfaestus` in order to use the interactive tool for navigating the VGS?

Thanks in advance!

**Comment by AndreaGuarracino** [comment]
Try using this Dockerfile https://github.com/chfi/gfaestus/issues/9#issuecomment-1160250301

**Comment by ekg** [comment]
@chfi you need to sort this out. There needs to be a way to cargo install
gfaestus and make it runnable with a basic CLI. Right now it's completely
non-documented. I suggest taking an hour to fix this and add basic
documentation for how to interact with gfaestus to the readme.

**Comment by davidebolo1993** [comment]
Hey @Overcraft90,

the executable is in /opt/gfaestus/target/release/gfaestus. 
I can't run docker in the HPC we have, but for singularity (very similar to docker):

```bash
singularity run gfaestus_v0.1.0.sif /opt/gfaestus/target/release/gfaestus --help
```

**Comment by Overcraft90** [comment]
Hello @davidebolo1993,

And thanks. However, just for me to understand since I'm running this on a local workstation, can the former line of command, or any other Dockerfile, be executed in local?

Also, it appears I cannot access the `gfaestus_v0.1.0.sif`, do I need to git clone the repository as well other than compiling the Dockerfile?

P.S. Just now I looked a bit into the singularity container, still I'm not aware of how to get the _**.sif**_ file

**Comment by davidebolo1993** [comment]
Hi @Overcraft90,

sorry I did not give more details in advance. 

_And thanks. However, just for me to understand since I'm running this on a local workstation, can the former line of command, or any other Dockerfile, be executed in local?_

Yes.

_Also, it appears I cannot access the gfaestus_v0.1.0.sif, do I need to git clone the repository as well other than compiling the Dockerfile?_

This is when you run this with singularity (I can't use docker in the cluster I have). Install Singularity first. Then pull the image and run gfaestus.

```bash
singularity pull docker://edg1983/gfaestus:v0.1.0
singularity run --nv gfaestus_v0.1.0.sif /opt/gfaestus/target/release/gfaestus
```

**Comment by Overcraft90** [comment]
OK, I will try as you said and let you know! Thanks again.

**Comment by Overcraft90** [comment]
Hi all, I have some updates

I installed `singularity`; however, I did it without realising there was an Debian/Ubuntu package installation I could follow instead of starting from the very beginning.

What I've done is installing both _dependencies_ & _Go_, then considering that downloading `Singularity` from release didn't work for me, I downloaded the **.deb** file and installed it with **apt**. When I run `singularity --version` it appears:

> singularity-ce version 3.10.0-jammy

so I thought everything was fine, and indeed when I run the commands @davidebolo1993 indicated in his message it seemed 'gfaestus' was working but then I got this message:

> WARN [gfaestus::vulkan::init] enumerating instance extension properties
> WARN [gfaestus::vulkan::init] "VK_EXT_debug_report"
> WARN [gfaestus::vulkan::init] "VK_EXT_debug_utils"
> WARN [gfaestus::vulkan::init] "VK_KHR_portability_enumeration"
> INFO [winit::platform_impl::platform::x11::window] Guessed window scale factor: 2
> ERROR [gfaestus] Error initializing Gfaestus
> ERROR [gfaestus] VkError(ERROR_INCOMPATIBLE_DRIVER)

after executing `singularity run --nv gfaestus_v0.1.0.sif /opt/gfaestus/target/release/gfaestus ../pangenome/pangenome_ref_guided_pggb.gfa ../pangenome/pangenome_ref_guided_pggb.og.lay.tsv`. Why is this happening? Is it because I missed out on something after installing the _dependencies _ & _GO_? Should I remove the `singularity` package so installed and go for the Debian/Ubuntu version with the following command:

```sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list && \
    sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 && \
    sudo apt-get update

    sudo apt-get install -y singularity-container
```
and, afterwards, define default configurations? Please, let me know. Thanks!

**Comment by chfi** [comment]
gfaestus' current graphics implementation isn't exactly doing everything correctly, so it has trouble running on less common hardware/more exotic Vulkan implementations. A switch to a new engine with much better compatibility is coming.

Can you show the output of running `vulkaninfo`?

**Comment by chfi** [comment]
Try forcing the use of other graphics by running gfaestus with the `--force-graphics-device "DEVICENAME"` option, where `DEVICENAME` is "Quadro RTX 4000", and then try with "Intel(R) UHD Graphics (CML GT2)". Also use the `--debug` flag.

If none of the devices work, it's probably a gfaestus bug.

**Comment by chfi** [comment]
Actually, it looks like gfaestus doesn't even know about the vulkan drivers, despite vulkaninfo working... 
This is the best I can find: https://askubuntu.com/questions/774131/installing-nvidia-vulkan-drivers-for-16-04/803110#803110

**Comment by Overcraft90** [comment]
Thanks @chfi,

I had the gut feeling it might have been something related to that based on the first output for the tool... I went through a lot of issues to set up the environment for using a scaffolding application taking advantage of GPU acceleration and this is my `nvidia-smi` config:
``` Wed Jun 22 12:17:05 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:01:00.0  On |                  N/A |
| N/A   59C    P0    41W /  N/A |    949MiB /  8192MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     13705      G   /usr/lib/xorg/Xorg                508MiB |
|    0   N/A  N/A     17475      G   /usr/bin/gnome-shell              170MiB |
|    0   N/A  N/A     18982      G   ...RendererForSitePerProcess       43MiB |
|    0   N/A  N/A     19082      G   ...veSuggestionsOnlyOnDemand      126MiB |
|    0   N/A  N/A     26390      G   ...507633976715190391,131072       97MiB |
+-----------------------------------------------------------------------------+
```
I'm running a _**510.73.05**_ which seems to be not easily recognised by `Vulkan`; in fact, at the following link [https://developer.nvidia.com/vulkan-driver](https://developer.nvidia.com/vulkan-driver) it is not even listed. 
The first thing I can think about is to update to the latest supported driver by `Vulkan` _e.g._ _**515.48.07**_, the problem is that I really don't want to mess up too much with GPU drivers as I crashed my previous system doing so. I might resort to the NVIDIA User Forum and ask to help on how to do it so that I don't screw up the machine, but any help is welcome.

What makes things difficult is that it is not possible to update the NVIDIA drivers from the _Software & Updates_ in Ubuntu, the latest one shown is the _**510**_, which I'm using.

If someone has some ideas, please let me know. Thanks in advance.

**Comment by chfi** [comment]
Yes, according to `vulkaninfo` both the Nvidia and Intel chips should be compatible with gfaestus, so I think the problem is that the Vulkan loader can't find the drivers, which is an environment issue. The docs for the loader may help: https://github.com/KhronosGroup/Vulkan-Loader

Does `vkcube` work? I also have another project, [waragraph](https://github.com/chfi/waragraph), which uses some more up-to-date libraries and makes more correct use of the Vulkan API, and should be more widely compatible.

**Comment by Overcraft90** [comment]
Thanks @chfi, I will have a look at the doc. In te meantime, I updated the NVIDIA drivers and I will test it again.

About `vcube` it works perfectly, which makes things even stranger..., I will also have a look into `waragraph`.

Let me know whether there is something else I can do. Thanks in advance!

**Comment by ekg** [comment]
It will be very helpful to know if waragraph works! Please let us know.

**Comment by Overcraft90** [comment]
@ekg Sure thing, I will! BTW, I run again the same command
```
singularity run --nv gfaestus_v0.1.0.sif /opt/gfaestus/target/release/gfaestus ../pangenome/pangenome_ref_guided_pggb.gfa ../pangenome/pangenome_ref_guided_pggb.og.lay.tsv
```
and I got exactly the same output..., I event tried the trick @AndreaGuarracino suggested me `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` but the result is still the same.

Thanks again to all of you!

**Comment by Overcraft90** [comment]
Hi again,

I'm happy to see there is a new version with _**cargo**_. This time I've been able to install it, since I'm visualizing the entire graph the output takes several minutes, and on a greater scale it looks a bit "coarse" (not easy to see specific/interesting regions); however, the tool works just fine. 

I'm planning on trying also `waragraph`, what is the main difference between the two? In other words why should I prefer/use one over the other or in what particular scenarios? Thanks again to both @chfi & @ekg for this new cool implementation!

**Comment by Overcraft90** [comment]
Hi @ekg, @chfi and @AndreaGuarracino,

 I will be attending the `MemPanG23` one of the requirement was to install `gfaestus`. I must say now that finally Vulkan decided to support `Ubuntu 22.04` things are much easier on that side; however, when installing the tool at first it prompts an error related to

> note: /usr/bin/ld: cannot find -lxcb-shape: No such file or directory
>           /usr/bin/ld: cannot find -lxcb-xfixes: No such file or directory
>           collect2: error: ld returned 1 exit status
>           
> 
> warning: `gfaestus` (bin "gfaestus") generated 13 warnings
> error: could not compile `gfaestus` due to previous error; 13 warnings emitted

which can be fixed with [the following](https://dev.to/amberisvibin/solving-rustc-cannot-find-lxcb-shape-oe9). Now, as I believe this could be the issue for other users, but could also help form the development side, I post here and close this old topic. After following the steps at the link above everything worked just fine.

**Comment by ekg** [comment]
Did you apt install libxcb-shape0-dev?

**Comment by Overcraft90** [comment]
Yes, I did but I believed it was something that should have been done during the `build`; in fact, there is not specific mention to it in the GitHub page...
